'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Bot, DollarSign, TrendingUp, Zap, Shield, Users, Clock, Sparkles, ChevronRight } from 'lucide-react'

export default function LandingPage() {
  const [email, setEmail] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleWaitlistSignup = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!email) return

    setIsSubmitting(true)
    
    try {
      // TODO: Implement actual API call
      await new Promise(resolve => setTimeout(resolve, 1000))
      alert('🎉 Welcome to the revolution! Check your email for early access.')
      setEmail('')
    } catch (error) {
      alert('Something went wrong. Please try again.')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="container-cyber flex items-center justify-between h-16">
          <div className="flex items-center space-x-2">
            <Bot className="h-8 w-8 text-cyber-400" />
            <span className="text-xl font-bold gradient-text">Agent Empire</span>
          </div>
          
          <div className="hidden md:flex items-center space-x-8">
            <Link href="#features" className="nav-link">Features</Link>
            <Link href="#how-it-works" className="nav-link">How It Works</Link>
            <Link href="#pricing" className="nav-link">Pricing</Link>
            <Link href="#testimonials" className="nav-link">Success Stories</Link>
          </div>
          
          <div className="flex items-center space-x-4">
            <Link href="/login" className="btn-ghost">Sign In</Link>
            <Link href="/signup" className="btn-cyber">
              Start Building <ArrowRight className="w-4 h-4 ml-2" />
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="section-cyber hero-gradient">
        <div className="container-cyber text-center">
          {/* Attention-Grabbing Badge */}
          <div className="inline-flex items-center px-4 py-2 rounded-full bg-cyber-500/10 border border-cyber-500/20 text-cyber-400 text-sm font-medium mb-8 animate-pulse-glow">
            <Sparkles className="w-4 h-4 mr-2" />
            🔥 10,000+ AI Agents Already Making Money
          </div>
          
          {/* Main Headline */}
          <h1 className="heading-1 gradient-text mb-6 animate-fade-in">
            Replace Your Job With AI Agents<br />
            <span className="text-neon-400 text-glow">That Make Money While You Sleep</span>
          </h1>
          
          {/* Subheadline */}
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8 animate-slide-up">
            Create, customize, and monetize AI agents that trade crypto, create viral content, 
            and perform tasks autonomously. Join the revolution where machines work 24/7 so you don't have to.
          </p>
          
          {/* Social Proof Numbers */}
          <div className="flex flex-wrap justify-center gap-8 mb-12 animate-slide-up">
            <div className="stat-card">
              <div className="stat-value text-neon-400">$2.4M+</div>
              <div className="stat-label">Generated by Agents</div>
            </div>
            <div className="stat-card">
              <div className="stat-value text-cyber-400">15,847</div>
              <div className="stat-label">Active Agents</div>
            </div>
            <div className="stat-card">
              <div className="stat-value text-electric-400">94%</div>
              <div className="stat-label">Success Rate</div>
            </div>
          </div>
          
          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <Link href="/signup" className="cta-button group">
              Create Your First Agent
              <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link href="/demo" className="btn-outline text-lg px-8 py-4 h-auto">
              Watch Live Demo
            </Link>
          </div>
          
          {/* Hero Visual */}
          <div className="relative max-w-4xl mx-auto">
            <div className="card-glass p-8 relative overflow-hidden">
              {/* Floating Agent Cards */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="agent-card text-left float-animation">
                  <div className="flex items-center mb-4">
                    <div className="agent-avatar mr-4">
                      <Bot className="w-8 h-8 text-white" />
                    </div>
                    <div>
                      <h4 className="font-bold text-white">CryptoTrader AI</h4>
                      <div className="flex items-center">
                        <div className="w-2 h-2 rounded-full agent-status-working mr-2"></div>
                        <span className="text-sm text-cyber-400">Trading</span>
                      </div>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm text-muted-foreground">24h Profit:</span>
                      <span className="earnings-positive">+$247.83</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm text-muted-foreground">Success Rate:</span>
                      <span className="text-neon-400">87%</span>
                    </div>
                  </div>
                </div>
                
                <div className="agent-card text-left float-animation" style={{ animationDelay: '1s' }}>
                  <div className="flex items-center mb-4">
                    <div className="agent-avatar mr-4">
                      <TrendingUp className="w-8 h-8 text-white" />
                    </div>
                    <div>
                      <h4 className="font-bold text-white">ViralContent AI</h4>
                      <div className="flex items-center">
                        <div className="w-2 h-2 rounded-full agent-status-online mr-2"></div>
                        <span className="text-sm text-cyber-400">Creating</span>
                      </div>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm text-muted-foreground">Posts Today:</span>
                      <span className="text-cyber-400">12</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm text-muted-foreground">Engagement:</span>
                      <span className="text-neon-400">94.2K</span>
                    </div>
                  </div>
                </div>
                
                <div className="agent-card text-left float-animation" style={{ animationDelay: '2s' }}>
                  <div className="flex items-center mb-4">
                    <div className="agent-avatar mr-4">
                      <DollarSign className="w-8 h-8 text-white" />
                    </div>
                    <div>
                      <h4 className="font-bold text-white">TaskMaster AI</h4>
                      <div className="flex items-center">
                        <div className="w-2 h-2 rounded-full agent-status-working mr-2"></div>
                        <span className="text-sm text-cyber-400">Automating</span>
                      </div>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm text-muted-foreground">Tasks Done:</span>
                      <span className="text-cyber-400">847</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm text-muted-foreground">Time Saved:</span>
                      <span className="text-neon-400">23.4h</span>
                    </div>
                  </div>
                </div>
              </div>
              
              {/* Cyber scan effect */}
              <div className="cyber-scan"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="section-cyber">
        <div className="container-cyber">
          <div className="text-center mb-16">
            <h2 className="heading-2 gradient-text mb-4">
              Why Everyone's Building AI Agents
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              The smartest people in tech are already using AI agents to automate their income. 
              Don't get left behind.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="feature-card">
              <Bot className="feature-icon" />
              <h3 className="text-xl font-bold mb-4">Autonomous Trading</h3>
              <p className="text-muted-foreground">
                AI agents analyze markets 24/7 and execute profitable trades while you sleep. 
                No emotions, no mistakes, just pure profit.
              </p>
            </div>
            
            <div className="feature-card">
              <TrendingUp className="feature-icon" />
              <h3 className="text-xl font-bold mb-4">Viral Content Creation</h3>
              <p className="text-muted-foreground">
                Generate engaging posts, memes, and videos that go viral. 
                Build massive followings and monetize your influence.
              </p>
            </div>
            
            <div className="feature-card">
              <Zap className="feature-icon" />
              <h3 className="text-xl font-bold mb-4">Task Automation</h3>
              <p className="text-muted-foreground">
                Automate research, data analysis, customer service, and more. 
                Your agents handle the work, you collect the results.
              </p>
            </div>
            
            <div className="feature-card">
              <Shield className="feature-icon" />
              <h3 className="text-xl font-bold mb-4">Risk Management</h3>
              <p className="text-muted-foreground">
                Built-in safety mechanisms protect your investments. 
                Smart stop-losses and position sizing keep you profitable.
              </p>
            </div>
            
            <div className="feature-card">
              <Users className="feature-icon" />
              <h3 className="text-xl font-bold mb-4">Agent Marketplace</h3>
              <p className="text-muted-foreground">
                Buy and sell successful agents. Own a piece of the most profitable 
                AI workers in the economy.
              </p>
            </div>
            
            <div className="feature-card">
              <Clock className="feature-icon" />
              <h3 className="text-xl font-bold mb-4">24/7 Operation</h3>
              <p className="text-muted-foreground">
                Never miss an opportunity. Your agents work around the clock, 
                maximizing profits while you focus on what matters.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="section-cyber bg-gradient-to-r from-cyber-950 to-electric-950">
        <div className="container-cyber">
          <div className="text-center mb-16">
            <h2 className="heading-2 text-white mb-4">
              From Zero to Profitable in 3 Steps
            </h2>
            <p className="text-lg text-gray-300 max-w-2xl mx-auto">
              Building your AI empire is simpler than you think. 
              No coding required, no technical skills needed.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-cyber-500 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold">
                1
              </div>
              <h3 className="text-xl font-bold text-white mb-4">Create Your Agent</h3>
              <p className="text-gray-300">
                Use our simple wizard to design your AI agent's personality, capabilities, 
                and goals. Takes less than 5 minutes.
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-electric-500 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold">
                2
              </div>
              <h3 className="text-xl font-bold text-white mb-4">Deploy & Configure</h3>
              <p className="text-gray-300">
                Connect your wallets and social accounts. Set your risk tolerance 
                and profit targets. Launch in one click.
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-neon-500 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold">
                3
              </div>
              <h3 className="text-xl font-bold text-white mb-4">Earn While You Sleep</h3>
              <p className="text-gray-300">
                Watch your agents work 24/7, generating income from trading, 
                content creation, and automated tasks.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="section-cyber bg-background">
        <div className="container-cyber">
          <div className="text-center mb-16">
            <h2 className="heading-2 gradient-text mb-4">
              Join Thousands of Successful Agent Builders
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Real people making real money with AI agents. These results speak for themselves.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="testimonial-card">
              <div className="flex items-center mb-4">
                <div className="w-12 h-12 bg-gradient-to-r from-cyber-400 to-electric-400 rounded-full mr-4"></div>
                <div>
                  <div className="font-bold">Sarah Chen</div>
                  <div className="text-sm text-muted-foreground">Ex-Google Engineer</div>
                </div>
              </div>
              <p className="text-muted-foreground mb-4">
                "My trading agent made $12,000 in the first month. I've replaced my entire salary 
                and now I'm building more agents. This is the future."
              </p>
              <div className="text-neon-400 font-bold">Monthly Earnings: $23,847</div>
            </div>
            
            <div className="testimonial-card">
              <div className="flex items-center mb-4">
                <div className="w-12 h-12 bg-gradient-to-r from-electric-400 to-neon-400 rounded-full mr-4"></div>
                <div>
                  <div className="font-bold">Marcus Rodriguez</div>
                  <div className="text-sm text-muted-foreground">Content Creator</div>
                </div>
              </div>
              <p className="text-muted-foreground mb-4">
                "My content agent grew my TikTok from 500 to 2.1M followers in 6 months. 
                The sponsorship deals are insane."
              </p>
              <div className="text-neon-400 font-bold">Followers Gained: 2.1M</div>
            </div>
            
            <div className="testimonial-card">
              <div className="flex items-center mb-4">
                <div className="w-12 h-12 bg-gradient-to-r from-neon-400 to-cyber-400 rounded-full mr-4"></div>
                <div>
                  <div className="font-bold">Jessica Park</div>
                  <div className="text-sm text-muted-foreground">Entrepreneur</div>
                </div>
              </div>
              <p className="text-muted-foreground mb-4">
                "Started with $500, now my agent portfolio is worth over $50K. 
                I'm buying and selling agents like stocks."
              </p>
              <div className="text-neon-400 font-bold">Portfolio Value: $54,293</div>
            </div>
          </div>
        </div>
      </section>

      {/* Urgency Section */}
      <section className="section-cyber bg-gradient-to-r from-red-950 to-orange-950">
        <div className="container-cyber text-center">
          <h2 className="heading-2 text-white mb-6">
            The AI Revolution Is Happening NOW
          </h2>
          <p className="text-lg text-gray-300 max-w-3xl mx-auto mb-8">
            McKinsey predicts 50% of jobs will be automated by 2030. You can either be 
            part of the problem or part of the solution. Choose to own the machines that replace humans.
          </p>
          
          <div className="grid md:grid-cols-3 gap-8 mb-12">
            <div className="text-center">
              <div className="text-3xl font-bold text-red-400 mb-2">50%</div>
              <div className="text-white">Jobs at risk by 2030</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-orange-400 mb-2">$16B</div>
              <div className="text-white">AI agent market size</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-yellow-400 mb-2">24/7</div>
              <div className="text-white">AI agents never sleep</div>
            </div>
          </div>
          
          <Link href="/signup" className="cta-button">
            Secure Your Future Now
            <ArrowRight className="w-5 h-5 ml-2" />
          </Link>
        </div>
      </section>

      {/* Final CTA */}
      <section className="section-cyber">
        <div className="container-cyber text-center">
          <h2 className="heading-1 gradient-text mb-6">
            Ready to Build Your AI Empire?
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-12">
            Join the thousands of people already earning passive income with AI agents. 
            The future belongs to those who act today.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/signup" className="cta-button group">
              Start Building Now
              <ChevronRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link href="/demo" className="btn-outline text-lg px-8 py-4 h-auto">
              See Live Demo
            </Link>
          </div>
          
          <p className="text-sm text-muted-foreground mt-8">
            No credit card required • Free to start • Join 10,000+ builders
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border bg-background/50 backdrop-blur-sm">
        <div className="container-cyber py-12">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center space-x-2 mb-4">
                <Bot className="h-6 w-6 text-cyber-400" />
                <span className="text-lg font-bold gradient-text">Agent Empire</span>
              </div>
              <p className="text-sm text-muted-foreground">
                The world's first platform for creating and monetizing AI agents. 
                Build your autonomous workforce today.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-4">Product</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/features" className="hover:text-foreground">Features</Link></li>
                <li><Link href="/pricing" className="hover:text-foreground">Pricing</Link></li>
                <li><Link href="/demo" className="hover:text-foreground">Demo</Link></li>
                <li><Link href="/api" className="hover:text-foreground">API</Link></li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-bold mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/about" className="hover:text-foreground">About</Link></li>
                <li><Link href="/blog" className="hover:text-foreground">Blog</Link></li>
                <li><Link href="/careers" className="hover:text-foreground">Careers</Link></li>
                <li><Link href="/contact" className="hover:text-foreground">Contact</Link></li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-bold mb-4">Resources</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/docs" className="hover:text-foreground">Documentation</Link></li>
                <li><Link href="/support" className="hover:text-foreground">Support</Link></li>
                <li><Link href="/community" className="hover:text-foreground">Community</Link></li>
                <li><Link href="/status" className="hover:text-foreground">Status</Link></li>
              </ul>
            </div>
          </div>
          
          <div className="border-t border-border mt-12 pt-8 flex flex-col sm:flex-row justify-between items-center">
            <p className="text-sm text-muted-foreground">
              © 2025 Agent Empire. All rights reserved.
            </p>
            <div className="flex space-x-6 mt-4 sm:mt-0">
              <Link href="/privacy" className="text-sm text-muted-foreground hover:text-foreground">
                Privacy
              </Link>
              <Link href="/terms" className="text-sm text-muted-foreground hover:text-foreground">
                Terms
              </Link>
              <Link href="/security" className="text-sm text-muted-foreground hover:text-foreground">
                Security
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}